name: Automation & Scripting Request
description: Related to task automation, script development, backup, and workflow automation.
title: "[Automation]: "
labels: ["automation", "scripting", "triage"]
assignees:
  - webera
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out with your Automation & Scripting needs! Please provide the necessary details.
  - type: dropdown
    id: service-type
    attributes:
      label: What type of automation or scripting service do you need?
      options:
        - Task Automation
        - Script Development
        - Automated Backups
        - Workflow Automation
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Please provide detailed information about your request
      description: Include any specific requirements, preferences, or existing systems that should be considered.
      placeholder: Share your needs and expectations here
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
