name: Specialized Support & Custom Solutions Request
description: Related to disaster recovery planning, custom integration development, legacy system migration, and hosting.
title: "[Specialized Support]: "
labels: ["custom-solutions", "specialized-support", "triage"]
assignees:
  - webera
body:
  - type: markdown
    attributes:
      value: |
        Thank you for selecting our Specialized Support & Custom Solutions services! Please provide the required details for your unique request.
  - type: dropdown
    id: service-type
    attributes:
      label: What specialized support or custom solution do you require?
      options:
        - Disaster Recovery Planning
        - Custom Integration Development
        - Legacy System Migration
        - Hosting
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Please provide a detailed description of your request
      description: Include any specific goals, technical requirements, or challenges that should be considered.
      placeholder: Explain your specific needs here
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false

